export const PERSONAS = [
  {
    email: 'andika@stekom.ac.id',
    nama: 'Andika Pratama',
    role: 'admin',
    jabatan: 'Manager HRD',
    phone: '+6281234567890',
    alamat: 'Jl. Merdeka No. 1, Jakarta',
    status: 'approved',
    weights: null,
  },
  {
    email: 'rudi@stekom.ac.id',
    nama: 'Rudi Hartono',
    role: 'karyawan',
    jabatan: 'Staff IT',
    phone: '+6281234567891',
    alamat: 'Jl. Sudirman No. 2, Jakarta',
    status: 'approved',
    weights: {
      hadir: 80,
      terlambat: 5,
      pulang_cepat: 10,
      izin: 3,
      sakit: 2,
      cuti: 0,
      tidakHadir: 0,
    },
  },
  {
    email: 'siti@stekom.ac.id',
    nama: 'Siti Rahmawati',
    role: 'karyawan',
    jabatan: 'Staff Keuangan',
    phone: '+6281234567892',
    alamat: 'Jl. Gatot Subroto No. 3, Jakarta',
    status: 'approved',
    weights: {
      hadir: 20,
      terlambat: 60,
      pulang_cepat: 5,
      izin: 5,
      sakit: 5,
      cuti: 0,
      tidakHadir: 5,
    },
  },
  {
    email: 'budi@stekom.ac.id',
    nama: 'Budi Santoso',
    role: 'karyawan',
    jabatan: 'Staff Baru',
    phone: '+6281234567893',
    alamat: 'Jl. Baru No. 1, Jakarta',
    status: 'pending',
    weights: null,
  },
  {
    email: 'dewi@stekom.ac.id',
    nama: 'Dewi Lestari',
    role: 'karyawan',
    jabatan: 'Staff Marketing',
    phone: '+6281234567894',
    alamat: 'Jl. Asia Afrika No. 4, Bandung',
    status: 'approved',
    weights: {
      hadir: 30,
      terlambat: 5,
      pulang_cepat: 5,
      izin: 40,
      sakit: 10,
      cuti: 0,
      tidakHadir: 10,
    },
  },
  {
    email: 'ani@stekom.ac.id',
    nama: 'Ani Susanti',
    role: 'karyawan',
    jabatan: 'Staff HR',
    phone: '+6281234567895',
    alamat: 'Jl. Diponegoro No. 5, Jakarta',
    status: 'approved',
    weights: {
      hadir: 85,
      terlambat: 5,
      pulang_cepat: 5,
      izin: 3,
      sakit: 2,
      cuti: 0,
      tidakHadir: 0,
    },
  },
  {
    email: 'tono@stekom.ac.id',
    nama: 'Tono Wibowo',
    role: 'karyawan',
    jabatan: 'Staff Gudang',
    phone: '+6281234567896',
    alamat: 'Jl. Pahlawan No. 6, Surabaya',
    status: 'approved',
    weights: {
      hadir: 40,
      terlambat: 10,
      pulang_cepat: 40,
      izin: 3,
      sakit: 2,
      cuti: 0,
      tidakHadir: 5,
    },
  },
  {
    email: 'ferry@stekom.ac.id',
    nama: 'Ferry Hermawan',
    role: 'karyawan',
    jabatan: 'Staff Magang',
    phone: '+6281234567897',
    alamat: 'Jl. Merapi No. 7, Yogyakarta',
    status: 'pending',
    weights: null,
  },
];

export const SAMPLE_PENGAJUAN = [
  {
    emailPrefix: 'rudi',
    jenis: 'cuti',
    tanggalMulai: '2026-07-28',
    tanggalSelesai: '2026-07-30',
    alasan: 'Acara keluarga',
    status: 'approved',
  },
  {
    emailPrefix: 'siti',
    jenis: 'izin',
    tanggalMulai: '2026-07-22',
    tanggalSelesai: '2026-07-22',
    alasan: 'Keperluan bank',
    status: 'approved',
  },
  {
    emailPrefix: 'dewi',
    jenis: 'izin',
    tanggalMulai: '2026-07-15',
    tanggalSelesai: '2026-07-15',
    alasan: 'Periksa kesehatan',
    status: 'approved',
  },
  {
    emailPrefix: 'dewi',
    jenis: 'sakit',
    tanggalMulai: '2026-07-20',
    tanggalSelesai: '2026-07-21',
    alasan: 'Demam',
    status: 'approved',
  },
  {
    emailPrefix: 'rudi',
    jenis: 'cuti',
    tanggalMulai: '2026-08-01',
    tanggalSelesai: '2026-08-03',
    alasan: 'Liburan tahunan',
    status: 'pending',
  },
];
