/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedKaryawanRouteImport } from './routes/_authenticated/_karyawan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedAdminHrdDashboardRouteImport } from './routes/_authenticated/_admin/hrd.dashboard'
import { Route as AuthenticatedAdminHrdKaryawanRouteImport } from './routes/_authenticated/_admin/hrd.karyawan'
import { Route as AuthenticatedAdminHrdPengajuanRouteImport } from './routes/_authenticated/_admin/hrd.pengajuan'
import { Route as AuthenticatedAdminHrdRiwayatRouteImport } from './routes/_authenticated/_admin/hrd.riwayat'
import { Route as AuthenticatedAdminHrdVerifikasiRouteImport } from './routes/_authenticated/_admin/hrd.verifikasi'
import { Route as AuthenticatedKaryawanAbsensiIndexRouteImport } from './routes/_authenticated/_karyawan/absensi/index'
import { Route as AuthenticatedKaryawanAbsensiRiwayatRouteImport } from './routes/_authenticated/_karyawan/absensi/riwayat'
import { Route as AuthenticatedKaryawanPengajuanIndexRouteImport } from './routes/_authenticated/_karyawan/pengajuan/index'
import { Route as AuthenticatedKaryawanPengajuanBaruRouteImport } from './routes/_authenticated/_karyawan/pengajuan/baru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKaryawanRoute = AuthenticatedKaryawanRouteImport.update({
  id: '/_karyawan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminHrdDashboardRoute =
  AuthenticatedAdminHrdDashboardRouteImport.update({
    id: '/hrd/dashboard',
    path: '/hrd/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrdKaryawanRoute =
  AuthenticatedAdminHrdKaryawanRouteImport.update({
    id: '/hrd/karyawan',
    path: '/hrd/karyawan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrdPengajuanRoute =
  AuthenticatedAdminHrdPengajuanRouteImport.update({
    id: '/hrd/pengajuan',
    path: '/hrd/pengajuan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrdRiwayatRoute =
  AuthenticatedAdminHrdRiwayatRouteImport.update({
    id: '/hrd/riwayat',
    path: '/hrd/riwayat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrdVerifikasiRoute =
  AuthenticatedAdminHrdVerifikasiRouteImport.update({
    id: '/hrd/verifikasi',
    path: '/hrd/verifikasi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedKaryawanAbsensiIndexRoute =
  AuthenticatedKaryawanAbsensiIndexRouteImport.update({
    id: '/absensi/',
    path: '/absensi/',
    getParentRoute: () => AuthenticatedKaryawanRoute,
  } as any)
const AuthenticatedKaryawanAbsensiRiwayatRoute =
  AuthenticatedKaryawanAbsensiRiwayatRouteImport.update({
    id: '/absensi/riwayat',
    path: '/absensi/riwayat',
    getParentRoute: () => AuthenticatedKaryawanRoute,
  } as any)
const AuthenticatedKaryawanPengajuanIndexRoute =
  AuthenticatedKaryawanPengajuanIndexRouteImport.update({
    id: '/pengajuan/',
    path: '/pengajuan/',
    getParentRoute: () => AuthenticatedKaryawanRoute,
  } as any)
const AuthenticatedKaryawanPengajuanBaruRoute =
  AuthenticatedKaryawanPengajuanBaruRouteImport.update({
    id: '/pengajuan/baru',
    path: '/pengajuan/baru',
    getParentRoute: () => AuthenticatedKaryawanRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/status': typeof AuthenticatedStatusRoute
  '/hrd/dashboard': typeof AuthenticatedAdminHrdDashboardRoute
  '/hrd/karyawan': typeof AuthenticatedAdminHrdKaryawanRoute
  '/hrd/pengajuan': typeof AuthenticatedAdminHrdPengajuanRoute
  '/hrd/riwayat': typeof AuthenticatedAdminHrdRiwayatRoute
  '/hrd/verifikasi': typeof AuthenticatedAdminHrdVerifikasiRoute
  '/absensi/riwayat': typeof AuthenticatedKaryawanAbsensiRiwayatRoute
  '/pengajuan/baru': typeof AuthenticatedKaryawanPengajuanBaruRoute
  '/absensi/': typeof AuthenticatedKaryawanAbsensiIndexRoute
  '/pengajuan/': typeof AuthenticatedKaryawanPengajuanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/status': typeof AuthenticatedStatusRoute
  '/hrd/dashboard': typeof AuthenticatedAdminHrdDashboardRoute
  '/hrd/karyawan': typeof AuthenticatedAdminHrdKaryawanRoute
  '/hrd/pengajuan': typeof AuthenticatedAdminHrdPengajuanRoute
  '/hrd/riwayat': typeof AuthenticatedAdminHrdRiwayatRoute
  '/hrd/verifikasi': typeof AuthenticatedAdminHrdVerifikasiRoute
  '/absensi/riwayat': typeof AuthenticatedKaryawanAbsensiRiwayatRoute
  '/pengajuan/baru': typeof AuthenticatedKaryawanPengajuanBaruRoute
  '/absensi': typeof AuthenticatedKaryawanAbsensiIndexRoute
  '/pengajuan': typeof AuthenticatedKaryawanPengajuanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_karyawan': typeof AuthenticatedKaryawanRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/_admin/hrd/dashboard': typeof AuthenticatedAdminHrdDashboardRoute
  '/_authenticated/_admin/hrd/karyawan': typeof AuthenticatedAdminHrdKaryawanRoute
  '/_authenticated/_admin/hrd/pengajuan': typeof AuthenticatedAdminHrdPengajuanRoute
  '/_authenticated/_admin/hrd/riwayat': typeof AuthenticatedAdminHrdRiwayatRoute
  '/_authenticated/_admin/hrd/verifikasi': typeof AuthenticatedAdminHrdVerifikasiRoute
  '/_authenticated/_karyawan/absensi/riwayat': typeof AuthenticatedKaryawanAbsensiRiwayatRoute
  '/_authenticated/_karyawan/pengajuan/baru': typeof AuthenticatedKaryawanPengajuanBaruRoute
  '/_authenticated/_karyawan/absensi/': typeof AuthenticatedKaryawanAbsensiIndexRoute
  '/_authenticated/_karyawan/pengajuan/': typeof AuthenticatedKaryawanPengajuanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profil'
    | '/status'
    | '/hrd/dashboard'
    | '/hrd/karyawan'
    | '/hrd/pengajuan'
    | '/hrd/riwayat'
    | '/hrd/verifikasi'
    | '/absensi/riwayat'
    | '/pengajuan/baru'
    | '/absensi/'
    | '/pengajuan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profil'
    | '/status'
    | '/hrd/dashboard'
    | '/hrd/karyawan'
    | '/hrd/pengajuan'
    | '/hrd/riwayat'
    | '/hrd/verifikasi'
    | '/absensi/riwayat'
    | '/pengajuan/baru'
    | '/absensi'
    | '/pengajuan'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_admin'
    | '/_authenticated/_karyawan'
    | '/_authenticated/dashboard'
    | '/_authenticated/profil'
    | '/_authenticated/status'
    | '/_authenticated/_admin/hrd/dashboard'
    | '/_authenticated/_admin/hrd/karyawan'
    | '/_authenticated/_admin/hrd/pengajuan'
    | '/_authenticated/_admin/hrd/riwayat'
    | '/_authenticated/_admin/hrd/verifikasi'
    | '/_authenticated/_karyawan/absensi/riwayat'
    | '/_authenticated/_karyawan/pengajuan/baru'
    | '/_authenticated/_karyawan/absensi/'
    | '/_authenticated/_karyawan/pengajuan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_karyawan': {
      id: '/_authenticated/_karyawan'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedKaryawanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/hrd/dashboard': {
      id: '/_authenticated/_admin/hrd/dashboard'
      path: '/hrd/dashboard'
      fullPath: '/hrd/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminHrdDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/hrd/karyawan': {
      id: '/_authenticated/_admin/hrd/karyawan'
      path: '/hrd/karyawan'
      fullPath: '/hrd/karyawan'
      preLoaderRoute: typeof AuthenticatedAdminHrdKaryawanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/hrd/pengajuan': {
      id: '/_authenticated/_admin/hrd/pengajuan'
      path: '/hrd/pengajuan'
      fullPath: '/hrd/pengajuan'
      preLoaderRoute: typeof AuthenticatedAdminHrdPengajuanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/hrd/riwayat': {
      id: '/_authenticated/_admin/hrd/riwayat'
      path: '/hrd/riwayat'
      fullPath: '/hrd/riwayat'
      preLoaderRoute: typeof AuthenticatedAdminHrdRiwayatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/hrd/verifikasi': {
      id: '/_authenticated/_admin/hrd/verifikasi'
      path: '/hrd/verifikasi'
      fullPath: '/hrd/verifikasi'
      preLoaderRoute: typeof AuthenticatedAdminHrdVerifikasiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_karyawan/absensi/': {
      id: '/_authenticated/_karyawan/absensi/'
      path: '/absensi'
      fullPath: '/absensi/'
      preLoaderRoute: typeof AuthenticatedKaryawanAbsensiIndexRouteImport
      parentRoute: typeof AuthenticatedKaryawanRoute
    }
    '/_authenticated/_karyawan/absensi/riwayat': {
      id: '/_authenticated/_karyawan/absensi/riwayat'
      path: '/absensi/riwayat'
      fullPath: '/absensi/riwayat'
      preLoaderRoute: typeof AuthenticatedKaryawanAbsensiRiwayatRouteImport
      parentRoute: typeof AuthenticatedKaryawanRoute
    }
    '/_authenticated/_karyawan/pengajuan/': {
      id: '/_authenticated/_karyawan/pengajuan/'
      path: '/pengajuan'
      fullPath: '/pengajuan/'
      preLoaderRoute: typeof AuthenticatedKaryawanPengajuanIndexRouteImport
      parentRoute: typeof AuthenticatedKaryawanRoute
    }
    '/_authenticated/_karyawan/pengajuan/baru': {
      id: '/_authenticated/_karyawan/pengajuan/baru'
      path: '/pengajuan/baru'
      fullPath: '/pengajuan/baru'
      preLoaderRoute: typeof AuthenticatedKaryawanPengajuanBaruRouteImport
      parentRoute: typeof AuthenticatedKaryawanRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminHrdDashboardRoute: typeof AuthenticatedAdminHrdDashboardRoute
  AuthenticatedAdminHrdKaryawanRoute: typeof AuthenticatedAdminHrdKaryawanRoute
  AuthenticatedAdminHrdPengajuanRoute: typeof AuthenticatedAdminHrdPengajuanRoute
  AuthenticatedAdminHrdRiwayatRoute: typeof AuthenticatedAdminHrdRiwayatRoute
  AuthenticatedAdminHrdVerifikasiRoute: typeof AuthenticatedAdminHrdVerifikasiRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminHrdDashboardRoute: AuthenticatedAdminHrdDashboardRoute,
  AuthenticatedAdminHrdKaryawanRoute: AuthenticatedAdminHrdKaryawanRoute,
  AuthenticatedAdminHrdPengajuanRoute: AuthenticatedAdminHrdPengajuanRoute,
  AuthenticatedAdminHrdRiwayatRoute: AuthenticatedAdminHrdRiwayatRoute,
  AuthenticatedAdminHrdVerifikasiRoute: AuthenticatedAdminHrdVerifikasiRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedKaryawanRouteChildren {
  AuthenticatedKaryawanAbsensiRiwayatRoute: typeof AuthenticatedKaryawanAbsensiRiwayatRoute
  AuthenticatedKaryawanPengajuanBaruRoute: typeof AuthenticatedKaryawanPengajuanBaruRoute
  AuthenticatedKaryawanAbsensiIndexRoute: typeof AuthenticatedKaryawanAbsensiIndexRoute
  AuthenticatedKaryawanPengajuanIndexRoute: typeof AuthenticatedKaryawanPengajuanIndexRoute
}

const AuthenticatedKaryawanRouteChildren: AuthenticatedKaryawanRouteChildren = {
  AuthenticatedKaryawanAbsensiRiwayatRoute:
    AuthenticatedKaryawanAbsensiRiwayatRoute,
  AuthenticatedKaryawanPengajuanBaruRoute:
    AuthenticatedKaryawanPengajuanBaruRoute,
  AuthenticatedKaryawanAbsensiIndexRoute:
    AuthenticatedKaryawanAbsensiIndexRoute,
  AuthenticatedKaryawanPengajuanIndexRoute:
    AuthenticatedKaryawanPengajuanIndexRoute,
}

const AuthenticatedKaryawanRouteWithChildren =
  AuthenticatedKaryawanRoute._addFileChildren(
    AuthenticatedKaryawanRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedKaryawanRoute: typeof AuthenticatedKaryawanRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedKaryawanRoute: AuthenticatedKaryawanRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
